# Configuration for language Italian
it:
  urlPrefix: ''
  languageName: ITA
  weight: 1
  contentDir: content/it

# Configuration for language English
en:
  urlPrefix: 'en/'
  languageName: ENG
  weight: 2
  contentDir: content/en

# Configuration for additional language
# xx:
#   languageName: XXX
#   weight: n+1
#   contentDir: content/xx