enteLink: 'http://teamdigitale.governo.it/en/'
footerColumn2Link: 'https://teamdigitale.governo.it/'

footerColumn1Links:
  -
    label: home-link
    url: '/'
    weight: 1
  -
    label: who-we-are-link
    url: 'whoweare'
    weight: 2
  -
    label: why-this-course-link
    url: 'why'
    weight: 3
  -
    label: episodes-link
    url: 'episodes'
    weight: 4
  -
    label: quiz-link
    url: 'quiz'
    weight: 5

footerBottomLinks:
  -
    label: legal-notes
    url: '#'
  -
    label: privacy-policy
    url: '#'

socials:
  medium:
    name: Medium
    URL: 'https://medium.com/team-per-la-trasformazione-digitale'
    icon: it-medium
  github:
    name: GitHub
    URL: 'https://github.com/teamdigitale/security-awareness'
    icon: it-github
  twitter:
    name: Twitter
    URL: 'https://twitter.com/teamdigitaleIT'
    icon: it-twitter
  linkedin:
    name: LinkedIn
    URL: 'https://www.linkedin.com/company/teamdigitale'
    icon: it-linkedin
  youtube:
    name: YouTube
    URL: 'https://www.youtube.com/channel/UCwOMMmrMXiktlvKXx4vHJ-g/'
    icon: it-youtube