socials:
  medium:
    name: Medium
    URL: 'https://medium.com/team-per-la-trasformazione-digitale'
    icon: it-medium
  github:
    name: GitHub
    URL: 'https://github.com/teamdigitale/security-awareness'
    icon: it-github
  twitter:
    name: Twitter
    URL: 'https://twitter.com/teamdigitaleIT'
    icon: it-twitter
  linkedin:
    name: LinkedIn
    URL: 'https://www.linkedin.com/company/teamdigitale'
    icon: it-linkedin
  youtube:
    name: YouTube
    URL: 'https://www.youtube.com/channel/UCwOMMmrMXiktlvKXx4vHJ-g/'
    icon: it-youtube