baseURL = "https://teamdigitale.github.io/security-awareness/"
theme = "hugo-theme-bootstrap-italia"

DefaultContentLanguage = "it"

publishDir = "./docs"

[Params]
  [Params.socials]
    [Params.socials.medium]
    name = "Medium"
    URL = "https://medium.com/team-per-la-trasformazione-digitale"
    icon = "it-medium"

    [Params.socials.github]
    name = "GitHub"
    URL = "https://github.com/teamdigitale/security-awareness"
    icon = "it-github"

    [Params.socials.twitter]
    name = "Twitter"
    URL = "https://twitter.com/teamdigitaleIT"
    icon = "it-twitter"

    [Params.socials.linkedin]
    name = "LinkedIn"
    URL = "https://www.linkedin.com/company/teamdigitale"
    icon = "it-linkedin"

    [Params.socials.youtube]
    name = "YouTube"
    URL = "https://www.youtube.com/channel/UCwOMMmrMXiktlvKXx4vHJ-g/"
    icon = "it-youtube"

[languages]
  [languages.it]
    title = "Sicurezza Digitale"
    ente = "Team per la Trasformazione Digitale"
    enteLink = "http://teamdigitale.governo.it"
    siteTitle = "Sicurezza Digitale"
    siteDescription = "per la Pubblica Amministrazione"
    languageName = "ITA"
    contentDir = "content/it"
    weight = 1

    footerColumn1Title = "Security Awareness"
    footerColumn1Text = "Un breve corso per la sicurezza digitale"
    footerColumn1Links = [
      { label = "Home", url = "/" },
      { label = "Chi siamo", url = "chisiamo" },
      { label = "Perchè questo corso?", url = "why" },
      { label = "Episodi", url = "episodes" },
      { label = "Quiz", url = "quiz" }
    ]

    footerColumn2Title = "Un progetto di"
    footerColumn2Text = "TEAM PER LA TRASFORMAZIONE DIGITALE"
    footerColumn2Link = "https://teamdigitale.governo.it/"

    footerBottomLinks = [
      { label = "Note legali", url = "#" },
      { label = "Privacy policy", url = "#" }
    ]

  [languages.en]
    title = "Digital Security"
    ente = "Digital Transformation Team"
    enteLink = "http://teamdigitale.governo.it/en/"
    siteTitle = "Digital Security"
    siteDescription = "For the Public Administration"
    languageName = "ENG"
    contentDir = "content/en"
    weight = 2

    footerColumn1Title = "Security Awareness"
    footerColumn1Text = "A short course for digital security"
    footerColumn1Links = [
      { label = "Home", url = "en" },
      { label = "Who are we", url = "en/whoweare" },
      { label = "Why this course?", url = "en/why" },
      { label = "Episodes", url = "en/episodes" },
      { label = "Quiz", url = "en/quiz" }
    ]

    footerColumn2Title = "A project by"
    footerColumn2Text = "DIGITAL TRANSFORMATION TEAM"
    footerColumn2Link = "https://teamdigitale.governo.it/en"

    footerBottomLinks = [
      { label = "Legal notes", url = "#" },
      { label = "Privacy policy", url = "#" }
    ]

  [languages.it.menu]
    [[languages.it.menu.main]]
      name = "Forum"
      URL = "https://forum.italia.it"
      weight = 2

    [[languages.it.menu.main]]
      name = "Docs"
      URL = "https://docs.italia.it"
      weight = 3

    [[languages.it.menu.main]]
      name = "Developers"
      URL = "https://developers.italia.it"
      weight = 4

    [[languages.it.menu.main]]
      name = "Designers"
      URL = "https://designers.italia.it"
      weight = 5
    
    [[languages.it.menu.navbar]]
      name = "Home"
      URL = "/"
      weight = 1

    [[languages.en.menu.navbar]]
      name = "Home"
      URL = "/"
      weight = 1

    [[languages.it.menu.navbar]]
      name = "Chi siamo"
      URL = "/chisiamo"
      weight = 2

    [[languages.en.menu.navbar]]
      name = "Who are we"
      URL = "/en/whoweare"
      weight = 2

    [[languages.it.menu.navbar]]
      name = "Perchè questo corso?"
      URL = "/why"
      weight = 3

    [[languages.en.menu.navbar]]
      name = "Why this course?"
      URL = "/en/why"
      weight = 3

    [[languages.it.menu.navbar]]
      name = "Episodi"
      URL = "/episodes"
      weight = 4

    [[languages.en.menu.navbar]]
      name = "Episodes"
      URL = "/en/episodes"
      weight = 4

    [[languages.it.menu.navbar]]
      name = "Quiz"
      URL = "/quiz"
      weight = 5

  [languages.en.menu]
    [[languages.en.menu.main]]
      name = "Forum"
      URL = "https://forum.italia.it"
      weight = 2

    [[languages.en.menu.main]]
      name = "Docs"
      URL = "https://docs.italia.it"
      weight = 3

    [[languages.en.menu.main]]
      name = "Developers"
      URL = "https://developers.italia.it"
      weight = 4

    [[languages.en.menu.main]]
      name = "Designers"
      URL = "https://designers.italia.it"
      weight = 5

    [[languages.en.menu.navbar]]
      name = "Quiz"
      URL = "/en/quiz"
      weight = 5