baseURL = "https://teamdigitale.github.io/security-awareness/"
theme = "hugo-theme-bootstrap-italia"

DefaultContentLanguage = "it"

publishDir = "./docs"

[Params]
  [Params.socials]
    [Params.socials.medium]
    name = "Medium"
    URL = "https://medium.com/team-per-la-trasformazione-digitale"
    icon = "it-medium"

    [Params.socials.github]
    name = "GitHub"
    URL = "https://github.com/teamdigitale/security-awareness"
    icon = "it-github"

    [Params.socials.twitter]
    name = "Twitter"
    URL = "https://twitter.com/teamdigitaleIT"
    icon = "it-twitter"

    [Params.socials.linkedin]
    name = "LinkedIn"
    URL = "https://www.linkedin.com/company/teamdigitale"
    icon = "it-linkedin"

    [Params.socials.youtube]
    name = "YouTube"
    URL = "https://www.youtube.com/channel/UCwOMMmrMXiktlvKXx4vHJ-g/"
    icon = "it-youtube"

[languages]
  [languages.it]
    title = "Corso di sicurezza digitale"
    ente = "Team per la Trasformazione Digitale"
    enteLink = "http://teamdigitale.governo.it"
    siteTitle = "Corso di base di sicurezza"
    siteDescription = "Corso di base di sicurezza digitale"
    languageName = "ITA"
    contentDir = "content/it"
    weight = 1

    footerColumn1Title = "Security Awareness"
    footerColumn1Text = "Un breve corso per la sicurezza digitale"
    footerColumn1Links = [
      { label = "Episodio 1 - Erorre Umano", url = "ep1" },
      { label = "Episodio 2 - Password Leak", url = "ep2" },
      { label = "Episodio 3 - Spearphishing", url = "ep3" },
      { label = "Episodio 4 - Ransomware", url = "ep4" },
      { label = "Quiz", url = "quiz" }
    ]

    footerColumn2Title = "Security Awareness"
    footerColumn2Text = "Security Awareness - Corso"

    footerBottomLinks = [
      { label = "Note legali", url = "#" },
      { label = "Privacy policy", url = "#" }
    ]

  [languages.en]
    title = "Course on the digital security"
    ente = "Digital Transformation Team"
    enteLink = "http://teamdigitale.governo.it/en/"
    siteTitle = "Base course on security"
    siteDescription = "Base course on digital security"
    languageName = "ENG"
    contentDir = "content/en"
    weight = 2

    footerColumn1Title = "Security Awareness"
    footerColumn1Text = "A short course for digital security"
    footerColumn1Links = [
      { label = "Episode 1 - Human Error", url = "en/ep1" },
      { label = "Episode 2 - Password Leak", url = "en/ep2" },
      { label = "Episode 3 - Spearphishing", url = "en/ep3" },
      { label = "Episode 4 - Ransomware", url = "en/ep3" },
      { label = "Quiz", url = "en/quiz" }
    ]

    footerColumn2Title = "Security Awareness"
    footerColumn2Text = "Security Awareness - Course"

    footerBottomLinks = [
      { label = "Legal notes", url = "#" },
      { label = "Privacy policy", url = "#" }
    ]

  [languages.it.menu]
    [[languages.it.menu.main]]
      name = "Forum"
      URL = "https://forum.italia.it"
      weight = 2

    [[languages.it.menu.main]]
      name = "Docs"
      URL = "https://docs.italia.it"
      weight = 3

    [[languages.it.menu.main]]
      name = "Developers"
      URL = "https://developers.italia.it"
      weight = 4

    [[languages.it.menu.main]]
      name = "Designers"
      URL = "https://designers.italia.it"
      weight = 5
    
    [[languages.it.menu.navbar]]
      name = "Home"
      URL = "/"
      weight = 1

    [[languages.en.menu.navbar]]
      name = "Home"
      URL = "/"
      weight = 1

    [[languages.it.menu.navbar]]
      name = "Episodi"
      weight = 2

    [[languages.en.menu.navbar]]
      name = "Episodes"
      weight = 2

    [[languages.it.menu.navbar]]
      name = "Episodio 1 - Errore Umano"
      URL = "/ep1"
      parent = "Episodi"
      weight = 1

    [[languages.it.menu.navbar]]
      name = "Episodio 2 - Password Leak"
      URL = "/ep2"
      parent = "Episodi"
      weight = 2

    [[languages.it.menu.navbar]]
      name = "Episodio 3 - Spearphishing"
      URL = "/ep3"
      parent = "Episodi"
      weight = 3

    [[languages.it.menu.navbar]]
      name = "Episodio 4 - Ransomware"
      URL = "/ep4"
      parent = "Episodi"
      weight = 4

    [[languages.it.menu.navbar]]
      name = "Quiz"
      URL = "/quiz"
      weight = 2

  [languages.en.menu]
    [[languages.en.menu.main]]
      name = "Forum"
      URL = "https://forum.italia.it"
      weight = 2

    [[languages.en.menu.main]]
      name = "Docs"
      URL = "https://docs.italia.it"
      weight = 3

    [[languages.en.menu.main]]
      name = "Developers"
      URL = "https://developers.italia.it"
      weight = 4

    [[languages.en.menu.main]]
      name = "Designers"
      URL = "https://designers.italia.it"
      weight = 5

    [[languages.en.menu.navbar]]
      name = "Episode 1 - Human Error"
      URL = "/en/ep1"
      parent = "Episodes"
      weight = 1

    [[languages.en.menu.navbar]]
      name = "Episode 2 - Password Leak"
      URL = "/en/ep2"
      parent = "Episodes"
      weight = 2

    [[languages.en.menu.navbar]]
      name = "Episode 3 - Spearphishing"
      URL = "/en/ep3"
      parent = "Episodes"
      weight = 3

    [[languages.en.menu.navbar]]
      name = "Episode 4 - Ransomware"
      URL = "/en/ep4"
      parent = "Episodes"
      weight = 4

    [[languages.en.menu.navbar]]
      name = "Quiz"
      URL = "/en/quiz"
      weight = 2